In [1]:
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split

# carrega o conjunto de dados CIFAR-10
cifar10 = fetch_openml('cifar_10', version=1, cache=True)

# separa os dados e os rótulos
X = cifar10.data
y = cifar10.target

# converte os rótulos para inteiros
y = y.astype(np.uint8)

# divide os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# normaliza os dados
X_train = X_train / 255.0
X_test = X_test/255.0

from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
###############
# SGDClassifier
from sklearn.linear_model import SGDClassifier
sgdc = SGDClassifier(random_state=42)

sgdc.fit(X_train, y_train) # executa o treinamento

sgdc_pred = sgdc.predict(X_test) # previsao

print("\nRelatorio SGDClassifier\n", classification_report(y_test, sgdc_pred))

cm = confusion_matrix(y_test, sgdc_pred)
print(cm)


Relatorio SGDClassifier
               precision    recall  f1-score   support

           0       0.71      0.12      0.21      1193
           1       0.50      0.46      0.48      1211
           2       0.27      0.13      0.17      1218
           3       0.26      0.02      0.04      1208
           4       0.36      0.18      0.24      1168
           5       0.26      0.34      0.29      1203
           6       0.24      0.72      0.36      1185
           7       0.32      0.51      0.40      1241
           8       0.48      0.48      0.48      1183
           9       0.44      0.42      0.43      1190

    accuracy                           0.34     12000
   macro avg       0.38      0.34      0.31     12000
weighted avg       0.38      0.34      0.31     12000

[[147  71  38   7  16 141 167 254 251 101]
 [  6 561  24   2  25  60 174 114  77 168]
 [ 18  29 154  15  79 188 464 186  55  30]
 [  5  46  51  27  52 287 503 149  37  51]
 [  6  18  88   5 206 142 452 198  27  26]


In [ ]:
##############
# RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(random_state=42)

rfc.fit(X_train, y_train)

rfc_pred = rfc.predict(X_test)

print("\nRelatorio RandomForestClassifier\n", classification_report(y_test, rfc_pred))

cm = confusion_matrix(y_test, rfc_pred)
print(cm)


Relatorio RandomForestClassifier
               precision    recall  f1-score   support

           0       0.54      0.55      0.54      1193
           1       0.50      0.55      0.52      1211
           2       0.37      0.31      0.34      1218
           3       0.33      0.28      0.30      1208
           4       0.37      0.40      0.39      1168
           5       0.39      0.36      0.38      1203
           6       0.46      0.53      0.49      1185
           7       0.52      0.44      0.48      1241
           8       0.61      0.63      0.62      1183
           9       0.46      0.54      0.50      1190

    accuracy                           0.46     12000
   macro avg       0.45      0.46      0.45     12000
weighted avg       0.45      0.46      0.45     12000

[[658  54  69  27  31  26  24  40 187  77]
 [ 42 660  17  37  29  30  47  38  65 246]
 [118  53 375  85 202  92 149  70  34  40]
 [ 64  56 103 335 104 210 161  67  28  80]
 [ 68  29 146  72 473  55 163  91 

In [2]:
##########
# KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
knc = KNeighborsClassifier()

knc.fit(X_train, y_train)

knc_pred = knc.predict(X_test)

print("\nRelatorio KNC\n", classification_report(y_test, knc_pred))

cm = confusion_matrix(y_test, knc_pred)
print("\nMatriz de confusão do KNC\n", cm)


Relatorio KNC
               precision    recall  f1-score   support

           0       0.36      0.54      0.43      1193
           1       0.69      0.21      0.32      1211
           2       0.22      0.43      0.30      1218
           3       0.31      0.23      0.26      1208
           4       0.23      0.48      0.31      1168
           5       0.40      0.22      0.28      1203
           6       0.36      0.28      0.31      1185
           7       0.68      0.21      0.32      1241
           8       0.40      0.68      0.51      1183
           9       0.71      0.13      0.22      1190

    accuracy                           0.34     12000
   macro avg       0.44      0.34      0.33     12000
weighted avg       0.44      0.34      0.33     12000


Matriz de confusão do KNC
 [[640   5 133  22  81  10  21   7 270   4]
 [158 250 144  45 192  38  78  17 259  30]
 [158   4 526  50 292  41  81   5  59   2]
 [106  10 266 275 228 123 115  17  63   5]
 [104   4 310  49 560  20